### ISSUE TITLE
Lightchain doesn't shutdown gracefuly since last Tendermint update 0.30

### ISSUE THREAD

**Issue by EnchanterIO** [lightstreams-network/lightchain#122] opened 2019-03-26 16:11 UTC
Could be related to not capturing wrong signal on MacOs only though:

<img width="1435" alt="Screen Shot 2019-03-26 at 17 07 54" src="https://user-images.githubusercontent.com/3595242/55013674-e46f8980-4fe9-11e9-8700-e0d4adbbbd55.png">

**Comment by ggarri** [comment] 2019-05-28 13:23
After replacing the proxyApp from a TCP socket to a local application this issue is not reproducible. 

After shutting down signal is sent the following output is generated:
```bash
ERROR[05-28|15:07:43.155] Connection failed @ recvRoutine (reading byte) engine=consensus module=p2p         peer=4172cede3e68412577965d0655597b9a7f235820@172.104.140.115:9001                    conn=MConn{172.104.140.115:9001} err="read tcp 192.168.1.99:58808->172.104.140.115:9001: use of closed network connection"
INFO [05-28|15:07:43.155] Stopping MConnection                     engine=consensus module=p2p         peer=4172cede3e68412577965d0655597b9a7f235820@172.104.140.115:9001                    impl=MConn{172.104.140.115:9001}
ERROR[05-28|15:07:43.155] Stopping peer for error                  engine=consensus module=p2p         peer="Peer{MConn{172.104.140.115:9001} 4172cede3e68412577965d0655597b9a7f235820 out}" err="read tcp 192.168.1.99:58808->172.104.140.115:9001: use of closed network connection"
INFO [05-28|15:07:43.155] Stopping Peer                            engine=consensus module=p2p         peer=4172cede3e68412577965d0655597b9a7f235820@172.104.140.115:9001                    impl="Peer{MConn{172.104.140.115:9001} 4172cede3e68412577965d0655597b9a7f235820 out}"
ERROR[05-28|15:07:43.156] Connection failed @ recvRoutine (reading byte) engine=consensus module=p2p         peer=0f04a32ffd95529c277e92aa9f006cc613595e54@172.104.140.115:9002                    conn=MConn{172.104.140.115:9002} err="read tcp 192.168.1.99:46396->172.104.140.115:9002: use of closed network connection"
INFO [05-28|15:07:43.156] Stopping MConnection                     engine=consensus module=p2p         peer=0f04a32ffd95529c277e92aa9f006cc613595e54@172.104.140.115:9002                    impl=MConn{172.104.140.115:9002}
ERROR[05-28|15:07:43.156] Stopping peer for error                  engine=consensus module=p2p         peer="Peer{MConn{172.104.140.115:9002} 0f04a32ffd95529c277e92aa9f006cc613595e54 out}" err="read tcp 192.168.1.99:46396->172.104.140.115:9002: use of closed network connection"
INFO [05-28|15:07:43.156] Stopping Peer                            engine=consensus module=p2p         peer=0f04a32ffd95529c277e92aa9f006cc613595e54@172.104.140.115:9002                    impl="Peer{MConn{172.104.140.115:9002} 0f04a32ffd95529c277e92aa9f006cc613595e54 out}"
INFO [05-28|15:07:43.156] Stopping EvidenceReactor                 engine=consensus module=evidence    impl=EvidenceReactor
INFO [05-28|15:07:43.156] Stopping PEXReactor                      engine=consensus module=pex         impl=PEXReactor
INFO [05-28|15:07:43.156] Stopping AddrBook                        engine=consensus module=p2p         book=/home/ggarrido/.lightchain/sirius/consensus/config/addrbook.json impl=AddrBook
INFO [05-28|15:07:43.156] Stopping MempoolReactor                  engine=consensus module=mempool     impl=MempoolReactor
INFO [05-28|15:07:43.156] Stopping BlockchainReactor               engine=consensus module=blockchain  impl=BlockchainReactor
INFO [05-28|15:07:43.156] Stopping ConsensusReactor                engine=consensus module=consensus   impl=ConsensusReactor
INFO [05-28|15:07:43.156] Stopping ConsensusState                  engine=consensus module=consensus   impl=ConsensusState
INFO [05-28|15:07:43.156] Stopping TimeoutTicker                   engine=consensus module=consensus   impl=TimeoutTicker
INFO [05-28|15:07:43.156] Saving AddrBook to file                  engine=consensus module=p2p         book=/home/ggarrido/.lightchain/sirius/consensus/config/addrbook.json size=2
INFO [05-28|15:07:43.156] Stopping baseWAL                         engine=consensus module=consensus   wal=/home/ggarrido/.lightchain/sirius/consensus/data/cs.wal/wal impl=baseWAL
INFO [05-28|15:07:43.160] Stopping Group                           engine=consensus module=consensus   wal=/home/ggarrido/.lightchain/sirius/consensus/data/cs.wal/wal impl=Group
ERROR[05-28|15:07:43.163] Stopped accept routine, as transport is closed engine=consensus module=p2p         numPeers=0
INFO [05-28|15:07:43.163] Closing rpc listener                     engine=consensus listener="&{Listener:0xc4201dad38 sem:0xc4249bb2c0 closeOnce:{m:{state:0 sema:0} done:0} done:0xc4249bb320}"
``` 

Every of those `ERROR` refers to p2p communications and we could consider them as acceptable as it is not affected any of the relevant element such a persisting and consensus. In addition, the usage of a Tendermint node also produces similar outputs during the shutdown.

For the reasoning described above I am inclined to close this issue.

**Closed by ggarri** 2019-05-28 13:23 UTC
Labels: bug
