### ISSUE TITLE
Unable to start node with Go 1.12

### ISSUE THREAD

**Issue by 0x13a** [lightstreams-network/lightchain#128] opened 2019-03-31 15:57 UTC
#### System information
```
Lightchain version: `Version: 1.0.0-beta MainNet`
OS & version: OSX Mojave 10.14.4 / Kernel Version Kernel Version 18.5.0:
Branch: master
Commit hash: e602722

```
#### Expected behaviour
node starts successfully

#### Actual behaviour
node does not start due to max fd allowance. Due to https://github.com/golang/go/issues/30401

#### Steps to reproduce the behaviour
- install Go 1.12
- try to start lightchain node

#### Console output (if applicable)

````
➜  lightchain git:(master) ✗ $GOPATH/bin/lightchain init --datadir=/Users/diegomariani/.lightchain
INFO [03-31|16:49:26.299] Maximum peer count                       ETH=25 LES=0 total=25
Fatal: Failed to raise file descriptor allowance: invalid argument
````

When using geth@master instead of 1.18 release it seems to work. Probably fixed with the next release of geth (1.19?)

**Comment by emizzle** [comment] 2019-05-15 05:20
I'm also having this exact same issue using:
```
Lightchain version: Version: 1.1.0-beta MainNet
OS & version: OSX Mojave 10.14.4 / Kernel Version 18.5.0
Go version: go version go1.12.5 darwin/amd64
Geth version: Version: 1.8.27-stable
```
Console output
```
$> lightchain init
INFO [05-15|15:18:19.939] Maximum peer count                       ETH=25 LES=0 total=25
Fatal: Failed to raise file descriptor allowance: invalid argument
```
@0x13a - you were able get this working by compiling the latest geth from master? Is that solution still working for you?

**Comment by EnchanterIO** [comment] 2019-05-15 07:57
Thx for reporting @0x13a, we will take care of it right after we finish some other topics. @emizzle you can always download the pre-compiled binary from our AWS S3 meanwhile. Here is the docs: https://docs.lightstreams.network/getting-started/install/

Or directly:

Mac:
```
wget "https://s3.eu-central-1.amazonaws.com/lightstreams-public/lightchain/latest/lightchain-osx" -O /usr/local/bin/lightchain
```

Linux (amd64):
```
wget "https://s3.eu-central-1.amazonaws.com/lightstreams-public/lightchain/latest/lightchain-linux-amd64" -O /usr/local/bin/lightchain
```

**Comment by 0x13a** [comment] 2019-05-15 11:33
@emizzle it works on the latest release of geth. Fixed here https://github.com/lightstreams-network/lightchain/pull/140 cc @EnchanterIO

**Comment by emizzle** [comment] 2019-05-16 00:27
Thanks @0x13a - I've built lightchain off your branch, until that fix is merged and a new release is cut.

**Comment by ggarri** [comment] 2019-05-16 10:15
Thanks @0x13a for the PR I have been reviewing and it is ready to be merged. The reasons for this update were on [`go-ethereum v1.8.24`](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.24)

**Closed by ggarri** 2019-05-16 10:15 UTC

**Comment by emizzle** [comment] 2019-05-17 03:22
Thanks @ggarri, I can confirm this works now!
